train:
    _target_: torch.utils.data.DataLoader
    batch_size: 4 #2
    num_workers: 4 #1
    pin_memory: False
    shuffle: True
    drop_last: True

val_default:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 2 #1
    pin_memory: False
    shuffle: False
